[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_9_0"]

[phases.install]
cmds = ["cd backend && npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && npm run start"